{{- if or .Values.enrollmentCode .Values.hubURL }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-lens-k8s-enrollment
type: Opaque
stringData:
  LENS_HUB_URL: {{ required "hubURL is required for enrollment" .Values.hubURL | quote }}
  LENS_ENROLLMENT_CODE: {{ required "enrollmentCode is required for enrollment" .Values.enrollmentCode | quote }}
{{- end }}
