import { useEffect, useState } from "react";
import { AlertCircle, ArrowRight, Bot, CheckCircle2, KeyRound, LoaderCircle, Network, PencilLine, PlugZap, Save, Search, ShieldAlert, ShieldCheck, type LucideIcon } from "lucide-react";
import { API, type CatalogSuggestion, type EntityContext, type ExposureDestination, type ExposureMap, type SystemItem } from "./api";

const categories: EntityContext["data_categories"] = ["personal", "health", "payment", "financial", "credentials", "source_code", "customer"];

export function InvestigationPage({ api, revision, onOpenGraph }: { api: API; revision: number; onOpenGraph: (systemID: string) => void }) {
  const [systems, setSystems] = useState<SystemItem[]>([]), [selectedID, setSelectedID] = useState(""), [exposure, setExposure] = useState<ExposureMap>();
  const [query, setQuery] = useState(""), [loading, setLoading] = useState(true), [detailLoading, setDetailLoading] = useState(false), [error, setError] = useState(""), [more, setMore] = useState(false);
  useEffect(() => { let active = true; setLoading(true); setError(""); const timer = window.setTimeout(() => api.systems({ limit: 100, sort: "last_seen", freshness: "fresh", search: query.trim() }).then((result) => { if (!active) return; const ordered = result.items.slice().sort(reviewOrder); setSystems(ordered); setMore(Boolean(result.next_cursor)); setSelectedID((current) => ordered.some((item) => item.id === current) ? current : initialSystem(ordered)?.id ?? ""); }).catch((reason) => active && setError(String(reason))).finally(() => active && setLoading(false)), query ? 220 : 0); return () => { active = false; window.clearTimeout(timer); }; }, [api, revision, query]);
  const reloadMap = () => { if (!selectedID) { setExposure(undefined); return; } setDetailLoading(true); api.exposureMap(selectedID).then(setExposure).catch((reason) => setError(String(reason))).finally(() => setDetailLoading(false)); };
  useEffect(reloadMap, [api, revision, selectedID]);
  const running = systems.filter((item) => item.state === "running").length, findings = systems.reduce((sum, item) => sum + (item.exposure_summary?.total ?? 0), 0), ownerGaps = systems.filter((item) => (item.exposure_summary?.counts.medium ?? 0) + (item.exposure_summary?.counts.low ?? 0) > 0).length;
  if (loading && !systems.length) return <ReviewState icon={LoaderCircle} title="Building the exposure queue" detail="Loading current systems from enrolled targets." spinning />;
  if (error && !systems.length) return <ReviewState icon={AlertCircle} title="The Exposure Map could not be loaded" detail={error} />;
  if (!systems.length && !query) return <ReviewState icon={Network} title="No current systems to assess" detail="Run an endpoint collector first. Lens never creates sample findings from absent evidence." />;
  return <div className="guided-review page-stack">
    <section className="review-story panel"><div><span>EXPLAINABLE EXPOSURE</span><h2>What can this AI system reach—and what should we investigate first?</h2><p>Follow observed configuration into public destinations, credential presence, operator context, and catalogue-derived potential without confusing any of them with invocation evidence.</p></div><div className="review-metrics"><ReviewMetric value={`${systems.length}${more ? "+" : ""}`} label="Current systems" /><ReviewMetric value={String(running)} label="Running now" active /><ReviewMetric value={String(findings)} label="Current findings" attention={findings > 0} /><ReviewMetric value={String(ownerGaps)} label="Need context review" attention={ownerGaps > 0} /></div></section>
    <section className="live-data-notice"><span><i /> THREE EVIDENCE BASES</span><p><b>Observed</b> collector facts, <b>operator context</b> supplied here, and <b>catalogue potential</b> are kept visibly separate.</p></section>
    <div className="review-workspace"><aside className="panel review-queue"><header><div><span>EXPOSURE QUEUE</span><h2>Choose a system</h2><p>Higher-severity findings appear first.</p></div><b>{systems.length}{more ? "+" : ""}</b></header><label><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search current systems" /></label><div className="review-system-list">{systems.map((item) => <button className={selectedID === item.id ? "active" : ""} onClick={() => setSelectedID(item.id)} key={item.id}><span><Bot size={16} /></span><div><b>{item.name}</b><small>{pretty(item.system_type)} · {item.exposure_summary?.total ?? 0} findings</small></div><StateLabel state={item.state} /></button>)}</div><p className="review-scale-note"><ShieldCheck size={13} /> Findings are categorical rule outcomes, not a composite risk score.</p></aside>
      <main className="panel review-detail">{detailLoading || !exposure ? <ReviewState icon={LoaderCircle} title="Resolving the exposure path" detail="Loading context, configured destinations, and current findings." spinning /> : <ExposureStory api={api} exposure={exposure} reload={reloadMap} onOpenGraph={onOpenGraph} />}</main></div>
    <ProductBoundary />
  </div>;
}

function ExposureStory({ api, exposure, reload, onOpenGraph }: { api: API; exposure: ExposureMap; reload: () => void; onOpenGraph: (id: string) => void }) {
  return <div className="system-story exposure-story"><header className="system-story-header"><div className="system-story-identity"><span><Bot size={22} /></span><div><p>SELECTED SYSTEM</p><h2>{exposure.system.name}</h2><small>{pretty(exposure.system.state)} · {exposure.destinations.length} configured destinations · {exposure.findings.length} current findings</small></div></div><button className="button subtle" onClick={() => onOpenGraph(exposure.system.id)}>Open evidence graph <ArrowRight size={14} /></button></header>
    <ContextEditor api={api} entityID={exposure.system.id} value={exposure.context} onSaved={reload} />
    <section className="exposure-section"><SectionHeading eyebrow="CONFIGURED PATHS" title="Where this system can reach" detail="Solid steps are observed. Dashed catalogue steps are potential—not access or use." count={exposure.destinations.length} />{exposure.destinations.length ? <div className="destination-list">{exposure.destinations.map((item) => <DestinationCard api={api} destination={item} reload={reload} key={item.id} />)}</div> : <p className="review-empty">No current MCP or API destination is connected to this system.</p>}</section>
    <section className="exposure-section"><SectionHeading eyebrow="PRIORITIZED FINDINGS" title="What to investigate first" detail="Every finding explains why it fired, the bounded evidence path, uncertainty, and a safe next check." count={exposure.findings.length} />{exposure.findings.length ? <div className="finding-list">{exposure.findings.map((finding) => <article className={`finding-card ${finding.severity}`} key={finding.id}><header><span className={`severity ${finding.severity}`}>{finding.severity}</span><div><h3>{finding.title}</h3><small>{finding.evidence_bases.map(pretty).join(" + ")}</small></div></header><div className="finding-path">{finding.path.map((step, index) => <span className={step.basis === "catalog_potential" ? "potential" : "observed"} key={`${step.entity_id}:${index}`}>{index > 0 && <i>→</i>}<b>{step.name}</b><small>{pretty(step.basis)}</small></span>)}</div><p><b>Why this fired</b>{finding.explanation}</p><p className="next-check"><CheckCircle2 size={14} /><span><b>Next check</b>{finding.recommended_next_step}</span></p></article>)}</div> : <div className="review-empty exposure-clear"><ShieldCheck size={18} /><p>No current rule findings. This is not a guarantee of safety; review missing context and unmapped APIs.</p></div>}</section>
  </div>;
}

function ContextEditor({ api, entityID, value, onSaved }: { api: API; entityID: string; value: EntityContext; onSaved: () => void }) {
  const [editing, setEditing] = useState(false), [draft, setDraft] = useState(value), [saving, setSaving] = useState(false), [error, setError] = useState(""); useEffect(() => setDraft(value), [value]);
  const save = () => { setSaving(true); setError(""); api.saveEntityContext(entityID, draft).then(() => { setEditing(false); onSaved(); }).catch((reason) => setError(String(reason))).finally(() => setSaving(false)); };
  return <section className="context-panel"><header><div><span>OPERATOR CONTEXT</span><h3>Ownership and data classification</h3><p>Audited assertions, separate from collector evidence.</p></div><button className="button subtle" onClick={() => editing ? save() : setEditing(true)} disabled={saving}>{editing ? <><Save size={13} /> {saving ? "Saving" : "Save context"}</> : <><PencilLine size={13} /> Edit context</>}</button></header>{editing ? <div className="context-form"><label><span>Owner</span><input maxLength={200} value={draft.owner_name ?? ""} onChange={(event) => setDraft({ ...draft, owner_name: event.target.value })} placeholder="Person or team" /></label><Select label="Owner type" value={draft.owner_type ?? ""} values={["person", "team"]} onChange={(owner_type) => setDraft({ ...draft, owner_type: owner_type as EntityContext["owner_type"] })} /><Select label="Environment" value={draft.environment ?? ""} values={["development", "test", "staging", "production"]} onChange={(environment) => setDraft({ ...draft, environment: environment as EntityContext["environment"] })} /><Select label="Criticality" value={draft.criticality ?? ""} values={["low", "medium", "high", "critical"]} onChange={(criticality) => setDraft({ ...draft, criticality: criticality as EntityContext["criticality"] })} /><Select label="Sensitivity" value={draft.sensitivity ?? ""} values={["public", "internal", "confidential", "restricted"]} onChange={(sensitivity) => setDraft({ ...draft, sensitivity: sensitivity as EntityContext["sensitivity"] })} /><Select label="Trust boundary" value={draft.trust_boundary ?? ""} values={["internal", "partner", "third_party"]} onChange={(trust_boundary) => setDraft({ ...draft, trust_boundary: trust_boundary as EntityContext["trust_boundary"] })} /><fieldset><legend>Data categories</legend>{categories.map((category) => <label key={category}><input type="checkbox" checked={draft.data_categories.includes(category)} onChange={() => setDraft({ ...draft, data_categories: draft.data_categories.includes(category) ? draft.data_categories.filter((item) => item !== category) : [...draft.data_categories, category] })} /> {pretty(category)}</label>)}</fieldset></div> : <div className="context-facts"><Fact label="Owner" value={value.owner_name ? `${value.owner_name} · ${pretty(value.owner_type ?? "owner")}` : "Not assigned"} attention={!value.owner_name} /><Fact label="Environment" value={pretty(value.environment ?? "Unknown")} /><Fact label="Criticality" value={pretty(value.criticality ?? "Unknown")} /><Fact label="Sensitivity" value={pretty(value.sensitivity ?? "Unknown")} /><Fact label="Trust boundary" value={pretty(value.trust_boundary ?? "Unknown")} /><Fact label="Data" value={value.data_categories.length ? value.data_categories.map(pretty).join(", ") : "Not classified"} /></div>}{error && <p className="inline-error">{error}</p>}</section>;
}
function Select({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <label><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}><option value="">Unknown</option>{values.map((item) => <option value={item} key={item}>{pretty(item)}</option>)}</select></label>; }

function DestinationCard({ api, destination, reload }: { api: API; destination: ExposureDestination; reload: () => void }) {
  const [query, setQuery] = useState(destination.host ?? destination.name), [suggestions, setSuggestions] = useState<CatalogSuggestion[]>([]), [error, setError] = useState("");
  const search = () => api.catalogSearch(query).then((result) => setSuggestions(result.items)).catch((reason) => setError(String(reason)));
  return <article className="destination-card"><header><span><PlugZap size={15} /></span><div><h3>{destination.name}</h3><small>{destination.host ?? pretty(String(destination.attributes.transport ?? "Custom connector"))}</small></div><div className="destination-flags">{destination.public_network && <b>Public network</b>}{destination.credential_present && <b><KeyRound size={11} /> Credential present</b>}</div></header><div className="path-visual"><span><Bot size={14} /> System</span><i /><span><PlugZap size={14} /> {pretty(destination.kind)}</span>{destination.catalog.status === "linked" && <><i className="potential" /><span className="potential"><Network size={14} /> {destination.catalog.name}</span></>}</div>
    <DestinationContext api={api} destination={destination} reload={reload} />
    {destination.catalog.status === "linked" ? <div className="catalog-capability"><div><span>CATALOGUE POTENTIAL</span><b>{destination.catalog.name}{destination.catalog.version ? ` · ${destination.catalog.version}` : ""}</b><small>{destination.catalog.match_basis}</small></div><div className="operation-counts">{Object.entries(destination.catalog.operation_counts).map(([kind, count]) => <span key={kind}><strong>{count}</strong>{pretty(kind)}</span>)}</div>{destination.catalog.representative_operations.length > 0 && <table><thead><tr><th>Class</th><th>Operation</th><th>Path</th></tr></thead><tbody>{destination.catalog.representative_operations.map((operation) => <tr key={`${operation.method}:${operation.path}`}><td>{pretty(operation.class)}</td><td>{operation.operation_id}</td><td>{operation.method} {operation.path}</td></tr>)}</tbody></table>}<p><ShieldAlert size={13} /> Potential only. Lens did not verify effective credential scope or invocation.</p></div> : <div className="catalog-unmapped"><AlertCircle size={15} /><div><b>API capabilities not mapped</b><p>No unique reviewed catalogue link exists. Lens will not invent operations from a fuzzy name.</p><button className="text-button" onClick={search}>Review catalogue suggestions</button></div></div>}
    {destination.catalog.status === "unmapped" && suggestions.length > 0 && <div className="catalog-suggestions"><label><Search size={12} /><input value={query} onChange={(event) => setQuery(event.target.value)} /><button onClick={search}>Search</button></label>{suggestions.slice(0, 8).map((item) => <button key={`${item.source_id}:${item.entry_id}`} onClick={() => api.linkCatalog(destination.id, item.source_id, item.entry_id).then(() => { setSuggestions([]); reload(); }).catch((reason) => setError(String(reason)))}><span><b>{item.api_family || item.name}</b><small>{item.provider}{item.version ? ` · ${item.version}` : ""}</small></span><ArrowRight size={13} /></button>)}</div>}{error && <p className="inline-error">{error}</p>}</article>;
}

function DestinationContext({ api, destination, reload }: { api: API; destination: ExposureDestination; reload: () => void }) {
  const [editing, setEditing] = useState(false), [owner, setOwner] = useState(destination.context.owner_name ?? ""), [ownerType, setOwnerType] = useState(destination.context.owner_type ?? ""), [boundary, setBoundary] = useState(destination.context.trust_boundary ?? ""), [error, setError] = useState("");
  const save = () => api.saveEntityContext(destination.id, { ...destination.context, owner_name: owner || undefined, owner_type: owner ? ownerType as EntityContext["owner_type"] : undefined, trust_boundary: boundary as EntityContext["trust_boundary"] || undefined }).then(() => { setEditing(false); reload(); }).catch((reason) => setError(String(reason)));
  return <div className="destination-context">{editing ? <><label>Owner<input value={owner} onChange={(event) => setOwner(event.target.value)} /></label><label>Type<select value={ownerType} onChange={(event) => setOwnerType(event.target.value)}><option value="">Choose</option><option value="person">Person</option><option value="team">Team</option></select></label><label>Trust boundary<select value={boundary} onChange={(event) => setBoundary(event.target.value)}><option value="">Unknown</option><option value="internal">Internal</option><option value="partner">Partner</option><option value="third_party">Third party</option></select></label><button className="text-button" onClick={save}>Save destination context</button></> : <><span>Owner: <b>{destination.context.owner_name ?? "Unknown"}</b></span><span>Trust boundary: <b>{pretty(destination.context.trust_boundary ?? "Unknown")}</b></span><button className="text-button" onClick={() => setEditing(true)}>Edit destination context</button></>}{error && <p className="inline-error">{error}</p>}</div>;
}

function ProductBoundary() { return <section className="review-boundary panel"><div><span>PRODUCT BOUNDARY</span><h2>Lens discovers and assesses exposure.</h2><p>It does not verify effective authorization, invoke tools, change credentials, remediate, or enforce policy.</p></div><div className="boundary-steps"><BoundaryStep number="01" title="Observe" detail="Collector evidence" /><BoundaryStep number="02" title="Contextualize" detail="Operator assertion" /><BoundaryStep number="03" title="Enrich" detail="Catalogue potential" /><BoundaryStep number="04" title="Investigate" detail="Safe next check" /></div></section>; }
function BoundaryStep({ number, title, detail }: { number: string; title: string; detail: string }) { return <div className="active"><span>{number}</span><b>{title}</b><small>{detail}</small></div>; }
function SectionHeading({ eyebrow, title, detail, count }: { eyebrow: string; title: string; detail: string; count?: number }) { return <header className="story-section-heading"><div><span>{eyebrow}</span><h2>{title}</h2><p>{detail}</p></div>{count !== undefined && <b>{count}</b>}</header>; }
function ReviewMetric({ value, label, active, attention }: { value: string; label: string; active?: boolean; attention?: boolean }) { return <div className={active ? "active" : attention ? "attention" : ""}><strong>{value}</strong><span>{label}</span></div>; }
function Fact({ label, value, attention }: { label: string; value: string; attention?: boolean }) { return <div><span>{label}</span><b className={attention ? "attention" : ""}>{value}</b></div>; }
function StateLabel({ state }: { state: string }) { return <i className={state === "running" ? "running" : state === "residual" ? "residual" : "observed"}>{pretty(state)}</i>; }
function ReviewState({ icon: Icon, title, detail, spinning }: { icon: LucideIcon; title: string; detail: string; spinning?: boolean }) { return <div className="review-state"><Icon className={spinning ? "spin" : ""} size={24} /><h2>{title}</h2><p>{detail}</p></div>; }
function initialSystem(items: SystemItem[]) { return items.find((item) => item.name === "OpenAI Codex" && item.state === "running") ?? items.find((item) => item.state === "running") ?? items[0]; }
function reviewOrder(left: SystemItem, right: SystemItem) { const rank = (item: SystemItem) => (item.exposure_summary?.counts.critical ?? 0) * 1000 + (item.exposure_summary?.counts.high ?? 0) * 100 + (item.exposure_summary?.counts.medium ?? 0) * 10 + (item.exposure_summary?.counts.low ?? 0); return rank(right) - rank(left) || Number(right.state === "running") - Number(left.state === "running") || left.name.localeCompare(right.name); }
function pretty(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
