import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { App } from "./App";
import "@xyflow/react/dist/style.css";
import "./styles/base.css";
import "./styles/auth.css";
import "./styles/shell.css";
import "./styles/overview.css";
import "./styles/data.css";
import "./styles/changes.css";
import "./styles/drawers.css";
import "./styles/evidence.css";
import "./styles/states.css";
import "./styles/readability.css";
import "./styles/inventory.css";
import "./styles/exposure-map.css";
import "./styles/dashboard.css";
import "./styles/executive.css";
import "./styles/guided-review.css";
import "./styles/self-serve.css";
import "./styles/overrides.css";
createRoot(document.getElementById("root")!).render(<StrictMode><App/></StrictMode>);
