image:
  repository: ghcr.io/barrikadelabs/barrikade-lens-k8s
  tag: "2.0.0"
  pullPolicy: IfNotPresent
existingSecret: lens-k8s-collector
clusterID: ""
clusterName: ""
resources:
  requests: {cpu: 50m, memory: 96Mi}
  limits: {cpu: 500m, memory: 256Mi}
persistence:
  enabled: true
  size: 64Mi
  storageClass: ""
